name = "Multiloop"
uuid = "2943ec09-40e8-48c8-98b3-cddee2160412"
authors = ["Kun Chen", "Daniel Cerkoney"]
version = "0.1.0"

[deps]
TaylorSeries = "6aa5eb33-94cf-58f4-a9d0-e4b2c4fc25ea"

[compat]
TaylorSeries = "0.12"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
